[workspace]
changelog_update = true
dependencies_update = true
pr_branch_prefix = "release-"
publish_timeout = "10m"

[[package]]
name = "arenabuddy"
publish = true
release = true
publish_no_verify = true
git_release_enable = true

[[package]]
name = "arenabuddy_data"
publish = true
release = true
git_release_enable = false

[[package]]
name = "arenabuddy_core"
publish = true
release = true
git_release_enable = false

[[package]]
name = "arenabuddy_cli"
publish = true
release = true
git_release_enable = false

[[package]]
name = "arenabuddy_ui"
publish = false
release = false
git_release_enable = false
