[build]
target = "./index.html"
# Output to the parent directory's dist for Tauri to find
dist = "../dist"

[watch]
ignore = ["../arenabuddy"]

[serve]
port = 1420
open = false
ws_protocol = "ws"

# Watch the core crate for changes too
watch = ["../arenabuddy_core"]
