use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use sqlx::FromRow;

/// Pitching line for a player in a game
#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct PitchingLine {
    pub id: i32,
    pub game_id: i32,
    pub player_id: i32,
    pub team_id: i32,
    pub pitch_order: Option<i32>,
    pub decision: Option<String>,
    pub ip: Option<Decimal>,
    pub h: Option<i32>,
    pub r: Option<i32>,
    pub er: Option<i32>,
    pub bb: Option<i32>,
    pub so: Option<i32>,
    pub hr: Option<i32>,
    pub era: Option<Decimal>,
    pub batters_faced: Option<i32>,
    pub pitches: Option<i32>,
    pub strikes: Option<i32>,
    pub strikes_contact: Option<i32>,
    pub strikes_swinging: Option<i32>,
    pub strikes_looking: Option<i32>,
    pub ground_balls: Option<i32>,
    pub fly_balls: Option<i32>,
    pub line_drives: Option<i32>,
    pub game_score: Option<i32>,
    pub inherited_runners: Option<i32>,
    pub inherited_scored: Option<i32>,
    pub wpa: Option<Decimal>,
    pub ali: Option<Decimal>,
    pub cwpa: Option<Decimal>,
    pub acli: Option<Decimal>,
    pub re24: Option<Decimal>,
}

/// Pitching line data for insertion
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct NewPitchingLine {
    pub game_id: i32,
    pub player_id: i32,
    pub team_id: i32,
    pub pitch_order: Option<i32>,
    pub decision: Option<String>,
    pub ip: Option<Decimal>,
    pub h: Option<i32>,
    pub r: Option<i32>,
    pub er: Option<i32>,
    pub bb: Option<i32>,
    pub so: Option<i32>,
    pub hr: Option<i32>,
    pub era: Option<Decimal>,
    pub batters_faced: Option<i32>,
    pub pitches: Option<i32>,
    pub strikes: Option<i32>,
    pub strikes_contact: Option<i32>,
    pub strikes_swinging: Option<i32>,
    pub strikes_looking: Option<i32>,
    pub ground_balls: Option<i32>,
    pub fly_balls: Option<i32>,
    pub line_drives: Option<i32>,
    pub game_score: Option<i32>,
    pub inherited_runners: Option<i32>,
    pub inherited_scored: Option<i32>,
    pub wpa: Option<Decimal>,
    pub ali: Option<Decimal>,
    pub cwpa: Option<Decimal>,
    pub acli: Option<Decimal>,
    pub re24: Option<Decimal>,
}
