[package]
name = "arenabuddy_ui"
description = "UI for arenabuddy"
authors.workspace = true
categories.workspace = true
version.workspace = true
repository.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true


[dependencies]
anyhow = { workspace = true }
arenabuddy_core = { path = "../arenabuddy_core/" }
arenabuddy_data = { path = "../arenabuddy_data" }
axum = { workspace = true, optional = true}
chrono = { workspace = true }
dioxus = { workspace = true, features = ["router", "desktop", "fullstack"] }
itertools = { workspace = true }
notify = { workspace = true }
open = "5.0"
postgresql_embedded = { workspace = true, features = ["bundled"] }
rfd = "0.14"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
start = { path = "../../lib/start"}
tokio = { workspace = true, optional = true, features = ["full"] }
tracing = { workspace = true }
tracingx = { path = "../../lib/tracingx" }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }

[lints]
workspace = true

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
server = ["dioxus/server", "dep:tokio"]
