[application]

[web.app]
title = "Arenabuddy"

[bundle]
identifier = "com.gazure.arenabuddy.dev"
publisher = "Grant Azure"
icon = ["arenabuddy/assets/icon.png"]
resources = ["arenabuddy/data/cards-full.pb"]
