apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: POST
      exemplarTraceIdDestinations:
        - datasourceUid: jaeger
          name: trace_id
    version: 1
    uid: prometheus-uid

  # Optional: Add Jaeger datasource for trace correlation
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: false
    editable: true
    jsonData:
      tracesToMetrics:
        datasourceUid: prometheus-uid
        tags: [{ key: 'service.name', value: 'service' }]
        queries:
          - name: 'Arenabuddy Games Rate'
            query: 'sum(rate(arenabuddy_games_ingested[$__rate_interval])) by (instance)'
    version: 1
    uid: jaeger

  # Direct connection to OpenTelemetry Collector Prometheus endpoint
  - name: OTel-Collector-Direct
    type: prometheus
    access: proxy
    url: http://otel-collector:8889
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
    version: 1
    uid: otel-collector-direct