apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    editable: true
    jsonData:
      nodeGraph:
        enabled: true

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: arenabuddy
    user: arenabuddy
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1700
    editable: true
