//! Renders fetched problems into solution modules and keeps `src/problems/` wired up.

use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
    sync::LazyLock,
};

use anyhow::Context;
use regex::Regex;

use crate::harness::{
    fetch::Question,
    parse::{self, ExampleTest},
};

/// Module name for a problem: `p0001_two_sum`. The `p` prefix keeps slugs like `3sum` valid
/// identifiers; zero-padding keeps lexicographic order equal to numeric order.
pub fn module_name(id: u32, slug: &str) -> String {
    format!("p{id:04}_{}", slug.replace('-', "_"))
}

/// Render the full source of a problem module.
pub fn render_module(question: &Question) -> anyhow::Result<String> {
    let id: u32 = question
        .question_frontend_id
        .parse()
        .with_context(|| format!("non-numeric frontend id {}", question.question_frontend_id))?;
    let content_html = question.content.as_deref().unwrap_or_default();
    let code = prepare_snippet(question.rust_snippet()?);
    let meta = question.meta();

    let doc = doc_comment(id, question, content_html);
    let uses = support_uses(&code);
    let fn_name = meta.as_ref().map(|m| camel_to_snake(&m.name)).unwrap_or_default();
    let example_tests = parse::build_example_tests(content_html, meta.as_ref());
    let tests = render_tests(&example_tests, &fn_name, &question.example_testcase_list);

    Ok(format!(
        "{doc}\n\
         // Generated by `leetcode fetch {id}`. Safe to edit; delete the allows below as you solve.\n\
         #![allow(\n\
         \x20   dead_code,\n\
         \x20   unused_imports,\n\
         \x20   unused_variables,\n\
         \x20   clippy::cast_possible_truncation,\n\
         \x20   clippy::cast_possible_wrap,\n\
         \x20   clippy::cast_sign_loss,\n\
         \x20   clippy::doc_markdown,\n\
         \x20   clippy::missing_panics_doc,\n\
         \x20   clippy::needless_pass_by_value,\n\
         \x20   clippy::unnecessary_wraps\n\
         )]\n\
         \n\
         {uses}{code}\n\
         #[cfg(test)]\n\
         mod tests {{\n\
         \x20   use super::*;\n\
         \n\
         {tests}\n\
         }}\n"
    ))
}

fn doc_comment(id: u32, question: &Question, content_html: &str) -> String {
    let mut lines = vec![
        format!("//! {id}. {} ({})", question.title, question.difficulty),
        "//!".to_string(),
        format!("//! <https://leetcode.com/problems/{}/>", question.title_slug),
    ];
    let body = parse::html_to_doc_text(content_html);
    if !body.is_empty() {
        lines.push("//!".to_string());
        for line in body.lines() {
            if line.is_empty() {
                lines.push("//!".to_string());
            } else {
                lines.push(format!("//! {line}"));
            }
        }
    }
    lines.join("\n")
}

/// Strip LeetCode's commented-out `// Definition for ...` preamble, inject `todo!()` into the
/// empty function bodies, and define the `Solution` struct the snippet references.
fn prepare_snippet(snippet: &str) -> String {
    static EMPTY_FN: LazyLock<Regex> =
        LazyLock::new(|| Regex::new(r"(?s)(fn\s+\w+\s*\([^)]*\)(?:\s*->\s*[^{]+?)?\s*\{)\s*\}").expect("valid regex"));

    let first_code_line = snippet
        .lines()
        .position(|line| {
            let trimmed = line.trim();
            !trimmed.is_empty() && !trimmed.starts_with("//")
        })
        .unwrap_or(0);
    let code = snippet.lines().skip(first_code_line).collect::<Vec<_>>().join("\n");
    let code = EMPTY_FN.replace_all(&code, "$1\n        todo!()\n    }");

    let mut out = String::new();
    if code.contains("impl Solution") {
        out.push_str("pub struct Solution;\n\n");
    }
    out.push_str(code.trim_end());
    out.push('\n');
    out
}

fn support_uses(code: &str) -> String {
    let mut uses = String::new();
    if code.contains("TreeNode") {
        uses.push_str("use std::{cell::RefCell, rc::Rc};\n\nuse crate::support::TreeNode;\n\n");
    }
    if code.contains("ListNode") {
        uses.push_str("use crate::support::ListNode;\n\n");
    }
    uses
}

fn camel_to_snake(name: &str) -> String {
    let mut out = String::new();
    for c in name.chars() {
        if c.is_ascii_uppercase() {
            out.push('_');
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

fn render_tests(tests: &[ExampleTest], fn_name: &str, raw_testcases: &[String]) -> String {
    if tests.is_empty() {
        let cases = raw_testcases
            .iter()
            .flat_map(|case| case.lines())
            .fold(String::new(), |mut acc, line| {
                acc.push_str("        // ");
                acc.push_str(line);
                acc.push('\n');
                acc
            });
        return format!(
            "    #[test]\n\
             \x20   #[ignore = \"no examples auto-parsed: write tests by hand\"]\n\
             \x20   fn example_1() {{\n\
             \x20       // Raw example testcases from LeetCode:\n\
             {cases}\
             \x20       todo!(\"write a test for this problem\");\n\
             \x20   }}"
        );
    }
    tests
        .iter()
        .enumerate()
        .map(|(i, test)| render_test(test, fn_name, i + 1))
        .collect::<Vec<_>>()
        .join("\n\n")
}

fn render_test(test: &ExampleTest, fn_name: &str, n: usize) -> String {
    match test {
        ExampleTest::Assert { args, expected, approx } => {
            let call = format!("Solution::{fn_name}({})", args.join(", "));
            if *approx {
                format!(
                    "    #[test]\n\
                     \x20   fn example_{n}() {{\n\
                     \x20       let result = {call};\n\
                     \x20       assert!((result - {expected}).abs() < 1e-5);\n\
                     \x20   }}"
                )
            } else {
                format!(
                    "    #[test]\n\
                     \x20   fn example_{n}() {{\n\
                     \x20       assert_eq!({call}, {expected});\n\
                     \x20   }}"
                )
            }
        }
        ExampleTest::Stub { input, output } => {
            let input = comment_safe(input);
            let output = comment_safe(output);
            format!(
                "    #[test]\n\
                 \x20   #[ignore = \"auto-parse failed: translate the example by hand\"]\n\
                 \x20   fn example_{n}() {{\n\
                 \x20       // Input: {input}\n\
                 \x20       // Output: {output}\n\
                 \x20       // Hint: see crate::support for ListNode/TreeNode builders.\n\
                 \x20       todo!(\"translate example into a test\");\n\
                 \x20   }}"
            )
        }
    }
}

fn comment_safe(text: &str) -> String {
    text.replace('\n', "\n        //         ")
}

/// Insert `pub mod <module>;` into a `mod.rs` body, keeping declarations sorted and idempotent.
pub fn insert_mod_line(content: &str, module: &str) -> String {
    let mut mods: BTreeSet<&str> = content
        .lines()
        .filter_map(|line| {
            line.trim()
                .strip_prefix("pub mod ")
                .and_then(|rest| rest.strip_suffix(';'))
        })
        .collect();
    mods.insert(module);
    let header: Vec<&str> = content
        .lines()
        .map(str::trim_end)
        .filter(|line| !line.trim_start().starts_with("pub mod ") && !line.is_empty())
        .collect();
    let mut out = String::new();
    if !header.is_empty() {
        out.push_str(&header.join("\n"));
        out.push_str("\n\n");
    }
    for module in mods {
        out.push_str("pub mod ");
        out.push_str(module);
        out.push_str(";\n");
    }
    out
}

pub fn problems_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src").join("problems")
}

/// Write the rendered module, refusing to clobber an existing scaffold unless `force`.
pub fn write_module(module: &str, contents: &str, force: bool) -> anyhow::Result<PathBuf> {
    let path = problems_dir().join(format!("{module}.rs"));
    if path.exists() && !force {
        anyhow::bail!("{} already exists (use --force to overwrite)", path.display());
    }
    fs::write(&path, contents).with_context(|| format!("writing {}", path.display()))?;
    Ok(path)
}

pub fn update_mod_rs(module: &str) -> anyhow::Result<()> {
    let path = problems_dir().join("mod.rs");
    let content = fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
    fs::write(&path, insert_mod_line(&content, module)).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

/// Best-effort format of a generated file; failures are logged and ignored.
pub fn run_rustfmt(path: &Path) {
    let status = std::process::Command::new("rustfmt")
        .args(["+nightly", "--edition", "2024"])
        .arg(path)
        .status();
    match status {
        Ok(status) if status.success() => {}
        Ok(status) => tracing::warn!(%status, "rustfmt exited non-zero (non-fatal)"),
        Err(err) => tracing::warn!(%err, "rustfmt failed to run (non-fatal)"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const TWO_SUM_SNIPPET: &str =
        "impl Solution {\n    pub fn two_sum(nums: Vec<i32>, target: i32) -> Vec<i32> {\n        \n    }\n}";

    fn two_sum_question() -> Question {
        serde_json::from_value(serde_json::json!({
            "questionFrontendId": "1",
            "title": "Two Sum",
            "titleSlug": "two-sum",
            "difficulty": "Easy",
            "isPaidOnly": false,
            "content": "<p>Given <code>nums</code> and <code>target</code>, return indices adding to target.</p>\n<pre>\n<strong>Input:</strong> nums = [2,7,11,15], target = 9\n<strong>Output:</strong> [0,1]\n</pre>",
            "codeSnippets": [{"lang": "Rust", "langSlug": "rust", "code": TWO_SUM_SNIPPET}],
            "exampleTestcaseList": ["[2,7,11,15]\n9"],
            "metaData": "{\"name\":\"twoSum\",\"params\":[{\"name\":\"nums\",\"type\":\"integer[]\"},{\"name\":\"target\",\"type\":\"integer\"}],\"return\":{\"type\":\"integer[]\"}}"
        }))
        .unwrap()
    }

    #[test]
    fn module_names() {
        assert_eq!(module_name(1, "two-sum"), "p0001_two_sum");
        assert_eq!(module_name(15, "3sum"), "p0015_3sum");
        assert_eq!(module_name(100, "same-tree"), "p0100_same_tree");
    }

    #[test]
    fn camel_to_snake_conversion() {
        assert_eq!(camel_to_snake("twoSum"), "two_sum");
        assert_eq!(camel_to_snake("findMedianSortedArrays"), "find_median_sorted_arrays");
        assert_eq!(camel_to_snake("isMatch"), "is_match");
    }

    #[test]
    fn renders_two_sum_module() {
        let rendered = render_module(&two_sum_question()).unwrap();
        assert!(rendered.starts_with("//! 1. Two Sum (Easy)\n//!\n//! <https://leetcode.com/problems/two-sum/>"));
        assert!(rendered.contains("#![allow("));
        assert!(rendered.contains("pub struct Solution;"));
        assert!(
            rendered.contains("pub fn two_sum(nums: Vec<i32>, target: i32) -> Vec<i32> {\n        todo!()\n    }"),
            "todo injected into empty body:\n{rendered}"
        );
        assert!(rendered.contains("assert_eq!(Solution::two_sum(vec![2, 7, 11, 15], 9), vec![0, 1]);"));
        assert!(rendered.contains("```text"));
        assert!(!rendered.contains("use crate::support"));
    }

    #[test]
    fn strips_definition_preamble_and_adds_support_use() {
        let snippet = "// Definition for singly-linked list.\n// #[derive(PartialEq, Eq, Clone, Debug)]\n// pub struct ListNode {\n//   pub val: i32,\n//   pub next: Option<Box<ListNode>>\n// }\nimpl Solution {\n    pub fn add_two_numbers(l1: Option<Box<ListNode>>, l2: Option<Box<ListNode>>) -> Option<Box<ListNode>> {\n        \n    }\n}";
        let code = prepare_snippet(snippet);
        assert!(!code.contains("Definition for"));
        assert!(code.starts_with("pub struct Solution;"));
        assert!(code.contains("todo!()"));
        assert_eq!(support_uses(&code), "use crate::support::ListNode;\n\n");
    }

    #[test]
    fn design_snippets_keep_their_own_struct() {
        let snippet = "struct LRUCache {\n\n}\nimpl LRUCache {\n    fn new(capacity: i32) -> Self {\n        \n    }\n\n    fn get(&self, key: i32) -> i32 {\n        \n    }\n}";
        let code = prepare_snippet(snippet);
        assert!(!code.contains("pub struct Solution;"));
        assert!(
            code.contains("struct LRUCache {\n\n}"),
            "struct body untouched:\n{code}"
        );
        assert_eq!(code.matches("todo!()").count(), 2);
    }

    #[test]
    fn tree_snippets_import_rc_refcell() {
        let uses = support_uses("pub fn invert_tree(root: Option<Rc<RefCell<TreeNode>>>)");
        assert!(uses.contains("use std::{cell::RefCell, rc::Rc};"));
        assert!(uses.contains("use crate::support::TreeNode;"));
    }

    #[test]
    fn mod_rs_insertion_is_sorted_and_idempotent() {
        let base = "//! Problems.\n\npub mod p0003_longest;\n";
        let inserted = insert_mod_line(base, "p0001_two_sum");
        assert_eq!(
            inserted,
            "//! Problems.\n\npub mod p0001_two_sum;\npub mod p0003_longest;\n"
        );
        assert_eq!(insert_mod_line(&inserted, "p0001_two_sum"), inserted);
        let appended = insert_mod_line(&inserted, "p0015_3sum");
        assert!(appended.ends_with("pub mod p0001_two_sum;\npub mod p0003_longest;\npub mod p0015_3sum;\n"));
    }

    #[test]
    fn empty_example_list_gets_raw_testcase_stub() {
        let tests = render_tests(&[], "two_sum", &["[2,7,11,15]\n9".to_string()]);
        assert!(tests.contains("#[ignore = \"no examples auto-parsed: write tests by hand\"]"));
        assert!(tests.contains("// [2,7,11,15]"));
        assert!(tests.contains("// 9"));
    }
}
