name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install system dependencies for Bevy, Dioxus, Protobuf, and GUI libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl \
            file \
            libglib2.0-dev \
            libasound2-dev \
            libayatana-appindicator3-dev \
            libgtk-3-dev \
            libcairo2-dev \
            libpango1.0-dev \
            libgdk-pixbuf2.0-dev \
            libatk1.0-dev \
            librsvg2-dev \
            libsoup-3.0-dev \
            libssl-dev \
            libudev-dev \
            libxdo-dev \
            libwebkit2gtk-4.1-dev \
            pkg-config \
            protobuf-compiler \
            wget

      - name: install cargo binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install Dioxus CLI
        run: cargo binstall dioxus-cli --version 0.7.0-alpha.3 --locked

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: check
        env:
          SQLX_OFFLINE: true
        run: cargo check --workspace --all-targets --all-features

      - name: clippy
        env:
          SQLX_OFFLINE: true
        run: cargo clippy --all --all-targets --all-features --examples --tests
